$directories = @(
    "apps/server/src/ws/handlers",
    "apps/server/src/ai/rag",
    "apps/server/src/routes",
    "apps/server/src/middleware",
    "apps/server/src/jobs",
    "apps/server/src/db/queries",
    "apps/web/app/(auth)",
    "apps/web/app/(chat)/[roomId]",
    "apps/web/app/(chat)/ai",
    "apps/web/app/api/auth/[...nextauth]",
    "apps/web/components/chat",
    "apps/web/components/sidebar",
    "apps/web/components/ai",
    "apps/web/components/shared",
    "apps/web/hooks",
    "apps/web/stores",
    "apps/admin/app/dashboard",
    "apps/admin/app/users",
    "apps/admin/app/safety",
    "apps/admin/app/rooms",
    "apps/admin/app/analytics",
    "apps/admin/components",
    "packages/ui",
    "packages/types",
    "packages/db/schema",
    "packages/config"
)

foreach ($dir in $directories) {
    $null = New-Item -ItemType Directory -Force -Path $dir
}

$files = @(
    "apps/server/src/ws/index.ts",
    "apps/server/src/ws/roomManager.ts",
    "apps/server/src/ai/router.ts",
    "apps/server/src/ai/suggest.ts",
    "apps/server/src/ai/safety.ts",
    "apps/server/src/ai/summarize.ts",
    "apps/server/src/ai/rag/embed.ts",
    "apps/server/src/ai/rag/retrieve.ts",
    "apps/server/src/ai/rag/assemble.ts",
    "apps/server/src/ai/directChat.ts",
    "apps/server/src/routes/auth.ts",
    "apps/server/src/routes/messages.ts",
    "apps/server/src/routes/rooms.ts",
    "apps/server/src/routes/users.ts",
    "apps/server/src/routes/ai.ts",
    "apps/server/src/middleware/auth.ts",
    "apps/server/src/middleware/rateLimiter.ts",
    "apps/server/src/middleware/sanitize.ts",
    "apps/server/src/middleware/audit.ts",
    "apps/server/src/jobs/embedWorker.ts",
    "apps/server/src/jobs/safetyWorker.ts",
    "apps/server/src/jobs/summaryWorker.ts",
    "apps/web/components/ai/DirectChat.tsx",
    "apps/web/hooks/useWebSocket.ts",
    "apps/web/hooks/useMessages.ts",
    "apps/web/hooks/usePresence.ts",
    "apps/web/hooks/useAISuggest.ts",
    "apps/web/hooks/useDirectChat.ts",
    "apps/web/stores/chatStore.ts",
    "apps/web/stores/aiStore.ts",
    "apps/web/stores/uiStore.ts",
    "apps/admin/components/SafetyFeed.tsx",
    "apps/admin/components/UserTable.tsx",
    "apps/admin/components/AIUsageChart.tsx",
    "packages/types/message.ts",
    "packages/types/user.ts",
    "packages/types/room.ts",
    "packages/types/ai.ts",
    "packages/types/ws-events.ts",
    "packages/db/schema/users.ts",
    "packages/db/schema/rooms.ts",
    "packages/db/schema/messages.ts",
    "packages/db/schema/embeddings.ts",
    "packages/db/schema/safety_flags.ts",
    "packages/db/schema/summaries.ts",
    "packages/db/schema/ai_chat_sessions.ts",
    "packages/db/schema/audit_log.ts",
    "packages/db/client.ts",
    "packages/config/eslint.config.js",
    "packages/config/tsconfig.base.json",
    "packages/config/tailwind.config.ts"
)

foreach ($file in $files) {
    $null = New-Item -ItemType File -Force -Path $file
}
